[servers]
server1 ansible_host=127.0.0.1 ansible_port=2221
server2 ansible_host=127.0.0.1 ansible_port=2222

[servers:vars]
ansible_user=ansible
ansible_password=ansible
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3
