spring.application.name=bank-redis

# =========================
# Redis
# =========================

spring.data.redis.host=localhost
spring.data.redis.port=6379


# =========================
# PostgreSQL
# =========================

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword


# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =========================
# Server
# =========================

server.port=8080
